package com.ryan.bts.models;
// Generated Jun 15, 2021, 10:58:05 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderId generated by hbm2java
 */
@Embeddable
public class OrderId implements java.io.Serializable {

	private long userId;
	private long itemId;

	public OrderId() {
	}

	public OrderId(long userId, long itemId) {
		this.userId = userId;
		this.itemId = itemId;
	}

	@Column(name = "user_id", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "item_id", nullable = false)
	public long getItemId() {
		return this.itemId;
	}

	public void setItemId(long itemId) {
		this.itemId = itemId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderId))
			return false;
		OrderId castOther = (OrderId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getItemId() == castOther.getItemId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37 * result + (int) this.getItemId();
		return result;
	}

}
