package com.ryan.bts.models;
// Generated Jun 15, 2021, 10:58:05 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.Builder;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", schema = "public")
@Builder
public class User implements java.io.Serializable {

	private long userId;
	private String username;
	private String name;
	private Set<Order> orders = new HashSet<Order>(0);

	public User() {
	}

	public User(long userId) {
		this.userId = userId;
	}

	public User(long userId, String username, String name, Set<Order> orders) {
		this.userId = userId;
		this.username = username;
		this.name = name;
		this.orders = orders;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
